---
title: 'supplementary'
author: "Maxime Dahirel & Chloé Guicharnaud"
date:
output:
  html_document:
    theme: yeti
    toc: TRUE
    toc_float: TRUE
    code_download: TRUE
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE, eval = FALSE)
```

```{r load-packages}
library(arm)
library(matrixStats)
library(tidyverse)
library(cowplot)
library(patchwork)
library(tidybayes)


library(cmdstanr)
library(brms)
options(mc.cores = 4)

library(tidyverse)

library(here)
```



```{r}
raw_data <- read_csv(here("NetLogo_output","model-output.csv"))
```

We rewrite variance variables to be in 0/1 mode to not be distracted

```{r}
data<- raw_data  %>% 
  mutate(is.VP_dmax=as.numeric(VP_logit_dmax >0),
           is.VP_DDD=as.numeric(VP_slope >0)) %>% 
  filter(ticks!=10)
```

what width do we use to define a "front" for sampling purposes?


```{r}
##supplementary plot to justify arbitrary front size =5 ish

data %>% 
  group_by(replicateID,ticks) %>% 
  mutate(front=max(pxcor*(N_predispersal>0))) %>% ###works with pre or post
  filter(pxcor>front-10) %>% ### do same plot with core
  ggplot()+
  geom_boxplot(aes(factor(front-pxcor),N_predispersal))+ ##works with pre or post
  geom_hline(aes(yintercept = K),col="red")+
  geom_vline(xintercept = 7,col="red")+
 facet_grid(rows=vars(dispersal_mortality,VP_logit_dmax),
               cols=vars(heritability,VP_slope))
```

